$(function(){
    $('.main_nav>li').mouseover(function(){
        $(this).children().stop().slideDown();
    });
     $('.main_nav>li').mouseleave(function(){
        $(this).children('.sub_nav').stop().slideUp();
    });
});
$(function(){
    setInterval(function(){
        $('.slide').delay('2500');
        $('.slide').animate({marginTop:'-300px'},500);
        $('.slide').delay('2500');
        $('.slide').animate({marginTop:'-600px'},500);
        $('.slide').delay('2500');
        $('.slide').animate({marginTop:'0'},500);
    });
});
$(function(){
    $('.팝업열기').click(function(){
        $('.popup').css('display','block');
    });
    $('.팝업닫기').click(function(){
        $('.popup').css('display','none');
    });
});